# action.gd --------------------------------
# Holds all logic for the actual action of a skill. For example, 
# this class would represent the actual fireball in world space
# generated by a fireball skill. Can be extended further.
@icon("res://icons/battle.png")
extends Area3D
class_name Action

@export var skill : Skill

@export_group("Visual")
@export var collideFX : PackedScene
@export var spawnFX : PackedScene

@export_group("ActionSettings")
@export var collideWithEnvironment : bool = false
@export var timeout : float = 0
@export var pierce : bool = false

var caster : Entity
var target : Entity

signal skillLockFinished
signal actionFinished
signal actionSpawned

func _ready():
	body_entered.connect(_on_action_collision)
	collision_layer = 8
	collision_mask = 16

	if collideWithEnvironment:
		set_collision_layer_value(1, true)

	if timeout > 0: timer_setup(stop, timeout)
	timer_setup(skillLockFinished.emit, skill.skillLock)
	
	for n in get_children():
		if n is ActionMod:
			n.call_deferred("set_action", self)


func _on_action_collision(body : Node3D) -> void:
	if body == caster: return
	if body is Entity: entity_hit(body)
	if !pierce: stop()


func spawn(_caster = null, _target = null) -> void:
	# logic depends on having a caster, always delete if the caster is null
	if !_caster: queue_free()

	caster = _caster

	if _target:
		target = _target
		target.entityDeath.connect(func(): target = null)

	actionSpawned.emit()


# called whenever the action should end, usually on collision.
func stop() -> void:
	skillLockFinished.emit()
	actionFinished.emit()
	queue_free()


func entity_hit(entity : Entity) -> void:
	if entity.stats:
		entity.take_damage(skill.calc_damage(caster), caster.stats, skill.dmgType)


func trigger_collideFX() -> void: add_child(collideFX.instantiate())
func trigger_spawnFX() -> void: add_child(spawnFX.instantiate())


func timer_setup(_onTimeout : Callable, time : float) -> Timer:
	var timer : Timer = Timer.new()
	timer.timeout.connect(_onTimeout)
	add_child(timer)
	timer.start(time)
	return timer
