# action.gd --------------------------------
# Holds all logic for the actual action of a skill. For example, 
# this class would represent the actual fireball in world space
# generated by a fireball skill. Can be extended further.
extends Node3D
class_name Action

@export var skill : Skill

@export_group("Node References")
@export var collider : Area3D

@export_group("Visual")
@export var collideFX : PackedScene
@export var spawnFX : PackedScene

var caster : Node3D
var target : CharacterBody3D

signal actionFinished

func _ready():
	collider.collision_layer = 8
	collider.collision_mask = 16
	collider.body_entered.connect(_on_action_collision)


func _on_action_collision(body : Node3D) -> void:
	if body == target:
		stop()


func spawn(t : CharacterBody3D, c : Node3D = null) -> void:
	caster = c
	target = t


# called whenever the action should end, usually on collision.
func stop() -> void:
	# random chance for everything for now
	if target is Entity: target.display_damage_num(randi_range(5, 20), 
		randf_range(0, 1)<=0.1, 
		randf_range(0, 1)<=0.1)
	actionFinished.emit()
	queue_free()


func trigger_collideFX() -> void: add_child(collideFX.instantiate())
func trigger_spawnFX() -> void: add_child(spawnFX.instantiate())
